language: scala
scala:
  - 2.12.6
  - 2.11.12
  - 2.13.0-M4
jdk:
  - oraclejdk8
services:
  - redis-server
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6380
  - sudo redis-server /etc/redis/redis.conf --port 6381
  - sudo redis-server /etc/redis/redis.conf --port 6382
